name: Deploy to Production

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy Code
        run: |
          cd /home/ubuntu/demo-production
          git pull origin production
          composer install
